version: '3.8'

services:
  mysql:
    context: ./mysql
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306

  adminer:
    context: ./adminer
    image: adminer
    container_name: adminer-container
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data: